import rasterio
import pandas as pd
import numpy as np

class Solar:
    def __init__(self,lista, path_ghi='./data/GHI', path_dni='./data/DNI', path_dif='./data/DIF', path_tmp='./data/TEMP') -> None:
        self.lista,self.path_ghi, self.path_dni, self.path_dif, self.path_tmp = lista, path_ghi, path_dni, path_dif, path_tmp
    
    def ghi(self,):
        filenames = ['Bolivia_GHI_kwhm2yr_01.tif', 'Bolivia_GHI_kwhm2yr_02.tif', 'Bolivia_GHI_kwhm2yr_03.tif',
                     'Bolivia_GHI_kwhm2yr_04.tif','Bolivia_GHI_kwhm2yr_05.tif','Bolivia_GHI_kwhm2yr_06.tif',
                     'Bolivia_GHI_kwhm2yr_07.tif','Bolivia_GHI_kwhm2yr_08.tif','Bolivia_GHI_kwhm2yr_09.tif',
                     'Bolivia_GHI_kwhm2yr_10.tif','Bolivia_GHI_kwhm2yr_11.tif','Bolivia_GHI_kwhm2yr_12.tif']
        
        src = rasterio.open(self.path_ghi+'/'+filenames[0])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_01 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_ghi+'/'+filenames[1])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_02 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_ghi+'/'+filenames[2])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_03 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_ghi+'/'+filenames[3])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_04 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_ghi+'/'+filenames[4])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_05 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_ghi+'/'+filenames[5])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_06 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_ghi+'/'+filenames[6])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_07 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_ghi+'/'+filenames[7])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_08 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_ghi+'/'+filenames[8])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_09 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_ghi+'/'+filenames[9])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_10 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_ghi+'/'+filenames[10])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_11 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_ghi+'/'+filenames[11])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_12 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        ghi_total = [ghi_01,ghi_02,ghi_03,ghi_04,ghi_05,ghi_06,ghi_07,
                    ghi_08,ghi_09,ghi_10,ghi_11,ghi_12]
        self.GHI_matriz = (np.transpose(np.array(ghi_total))).reshape((len(self.lista),12))
        print(self.GHI_matriz)
    def dhi(self,):
        filenames = ['Bolivia_DNI_kwhm2yr_01.tif', 'Bolivia_DNI_kwhm2yr_02.tif', 'Bolivia_DNI_kwhm2yr_03.tif',
                     'Bolivia_DNI_kwhm2yr_04.tif','Bolivia_DNI_kwhm2yr_05.tif','Bolivia_DNI_kwhm2yr_06 .tif',
                     'Bolivia_DNI_kwhm2yr_07.tif','Bolivia_DNI_kwhm2yr_08.tif','Bolivia_DNI_kwhm2yr_09.tif',
                     'Bolivia_DNI_kwhm2yr_10.tif','Bolivia_DNI_kwhm2yr_11.tif','Bolivia_DNI_kwhm2yr_12.tif']
        
        src = rasterio.open(self.path_dni+'/'+filenames[0])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_01 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dni+'/'+filenames[1])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_02 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dni+'/'+filenames[2])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_03 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dni+'/'+filenames[3])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_04 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dni+'/'+filenames[4])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_05 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dni+'/'+filenames[5])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_06 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dni+'/'+filenames[6])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_07 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dni+'/'+filenames[7])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_08 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dni+'/'+filenames[8])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_09 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dni+'/'+filenames[9])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_10 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dni+'/'+filenames[10])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_11 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dni+'/'+filenames[11])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_12 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        ghi_total = [ghi_01,ghi_02,ghi_03,ghi_04,ghi_05,ghi_06,ghi_07,
                    ghi_08,ghi_09,ghi_10,ghi_11,ghi_12]
        self.DNI_matriz = (np.transpose(np.array(ghi_total))).reshape((len(self.lista),12))
        print(self.DNI_matriz)
    def dif(self,):
        filenames = ['Bolivia_DIF_kwhm2yr_01.tif', 'Bolivia_DIF_kwhm2yr_02.tif', 'Bolivia_DIF_kwhm2yr_03.tif',
                     'Bolivia_DIF_kwhm2yr_04.tif','Bolivia_DIF_kwhm2yr_05.tif','Bolivia_DIF_kwhm2yr_06.tif',
                     'Bolivia_DIF_kwhm2yr_07.tif','Bolivia_DIF_kwhm2yr_08.tif','Bolivia_DIF_kwhm2yr_09.tif',
                     'Bolivia_DIF_kwhm2yr_10.tif','Bolivia_DIF_kwhm2yr_11.tif','Bolivia_DIF_kwhm2yr_12.tif']
        
        src = rasterio.open(self.path_dif+'/'+filenames[0])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_01 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dif+'/'+filenames[1])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_02 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dif+'/'+filenames[2])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_03 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dif+'/'+filenames[3])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_04 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dif+'/'+filenames[4])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_05 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dif+'/'+filenames[5])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_06 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dif+'/'+filenames[6])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_07 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dif+'/'+filenames[7])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_08 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dif+'/'+filenames[8])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_09 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dif+'/'+filenames[9])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_10 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dif+'/'+filenames[10])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_11 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_dif+'/'+filenames[11])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_12 = (np.array(value)/365).reshape((1, len(self.lista)))
        src.close()
        ghi_total = [ghi_01,ghi_02,ghi_03,ghi_04,ghi_05,ghi_06,ghi_07,
                    ghi_08,ghi_09,ghi_10,ghi_11,ghi_12]
        self.DIF_matriz = (np.transpose(np.array(ghi_total))).reshape((len(self.lista),12))
        print(self.DIF_matriz)
      
    def tmp(self,):
        filenames = ['Bolivia_tempC_01.tif', 'Bolivia_tempC_02.tif', 'Bolivia_tempC_03.tif',
                     'Bolivia_tempC_04.tif','Bolivia_tempC_05.tif','Bolivia_tempC_06.tif',
                     'Bolivia_tempC_07.tif','Bolivia_tempC_08.tif','Bolivia_tempC_09.tif',
                     'Bolivia_tempC_10.tif','Bolivia_tempC_11.tif','Bolivia_tempC_12.tif']
        
        src = rasterio.open(self.path_tmp+'/'+filenames[0])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_01 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_tmp+'/'+filenames[1])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_02 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_tmp+'/'+filenames[2])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_03 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_tmp+'/'+filenames[3])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_04 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_tmp+'/'+filenames[4])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_05 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_tmp+'/'+filenames[5])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_06 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_tmp+'/'+filenames[6])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_07 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_tmp+'/'+filenames[7])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_08 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_tmp+'/'+filenames[8])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_09 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_tmp+'/'+filenames[9])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_10 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_tmp+'/'+filenames[10])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_11 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        src = rasterio.open(self.path_tmp+'/'+filenames[11])
        value = list(rasterio.sample.sample_gen(src, self.lista))
        ghi_12 = (np.array(value)).reshape((1, len(self.lista)))
        src.close()
        ghi_total = [ghi_01,ghi_02,ghi_03,ghi_04,ghi_05,ghi_06,ghi_07,
                    ghi_08,ghi_09,ghi_10,ghi_11,ghi_12]
        self.TMP_matriz = (np.transpose(np.array(ghi_total))).reshape((len(self.lista),12))
        print(self.TMP_matriz)
        

